spring:
  application:
    name: ai-code-generator-backend
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code_generator
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      ttl: 3600
server:
  port: 8001
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
      timeout: 2592000
# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zzy.aicodegenerator.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# langchain4j配置

langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com/
      api-key:
      model-name: deepseek-v4-flash
      log-requests: true
      log-responses: true
      max-tokens: 8192
#      strict-json-schema: true
#      response-format: json_object

minio:
  # 必须填 9000 端口（API 端口），千万不要填 9001 网页控制台端口！
  endpoint: http://localhost:9000
  accessKey: minio
  secretKey: 123456
  # 预设一个默认的存储桶（桶名称不能包含大写字母和下划线，只能小写字母、数字和连字符）
  bucketName: ai-code-generator